export enum Role {
  // SUPERADMIN = 'superadmin',
  ADMIN = 'ADMIN',
  USER = 'USER',
  PROPERTY_MANAGER = 'PROPERTY_MANAGER',
  AUTHORIZED_VIEWER = 'AUTHORIZED_VIEWER',
  OPERATIONAL = 'OPERATIONAL',
}
